### ISSUE TITLE
fatal error: octomap/OcTreeLUT.h: No such file or directory

### ISSUE THREAD

**Issue by YiChenCityU** [XinkeAE/Active-ORB-SLAM2#1]
Hi, I have encountered this error when building. Do you have any idea? Thanks very much.
```
In file included from /home/eason/Documents/Active-ORB-SLAM2-master/src/OctomapBuilder.cc:1:0:
/home/eason/Documents/Active-ORB-SLAM2-master/include/OctomapBuilder.h:15:31: fatal error: octomap/OcTreeLUT.h: No such file or directory
compilation terminated.
CMakeFiles/ORB_SLAM2.dir/build.make:686: recipe for target 'CMakeFiles/ORB_SLAM2.dir/src/OctomapBuilder.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/OctomapBuilder.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/eason/Documents/Active-ORB-SLAM2-master/include/System.h:40:0,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Viewer.h:28,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Tracking.h:29,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/LocalMapping.h:27,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/LoopClosing.h:25,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Optimizer.h:27,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/src/Initializer.cc:25:
/home/eason/Documents/Active-ORB-SLAM2-master/include/OctomapBuilder.h:15:31: fatal error: octomap/OcTreeLUT.h: No such file or directory
compilation terminated.
In file included from /home/eason/Documents/Active-ORB-SLAM2-master/include/System.h:40:0,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Viewer.h:28,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Tracking.h:29,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/FrameDrawer.h:24,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/src/FrameDrawer.cc:21:
/home/eason/Documents/Active-ORB-SLAM2-master/include/OctomapBuilder.h:15:31: fatal error: octomap/OcTreeLUT.h: No such file or directory
compilation terminated.
In file included from /home/eason/Documents/Active-ORB-SLAM2-master/include/System.h:40:0,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Viewer.h:28,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/include/Tracking.h:29,
                 from /home/eason/Documents/Active-ORB-SLAM2-master/src/Tracking.cc:22:
/home/eason/Documents/Active-ORB-SLAM2-master/include/OctomapBuilder.h:15:31: fatal error: octomap/OcTreeLUT.h: No such file or directory
compilation terminated.

```

**Comment by zzx9636** [comment]
Hi, thanks for your questions. Have you installed ros-version-octomap in your computer? If you do, can you tell me which version is your ROS. We tested our system in ROS indigo.

**Comment by YiChenCityU** [comment]
Hi, I have installed the octomap  based on it's github. My linux version is kinetic. Could you write the installation with more detail? And do you have some video to show the result? Thanks very much.

**Comment by zzx9636** [comment]
Thanks for your reply. We will definitely write an detailed instructions. For the video, I will upload it to YouTube later today. At the mean while, I will also look into the error.

**Comment by XinkeAE** [comment]
The system was developed based on the octmap provided in ros-indigo. I believe it is an older version of octmap and some functions or files such as the ones in OcTreeLUT.h are depreciated in the newer version of ROS or octomap. We will look into the problem and see if there is a way to support the current octomap.

**Comment by WR0903** [comment]
In file included from /home/wr/catkin_ws/src/Active-ORB-SLAM2/include/Tracking.h:42:0,
                 from /home/wr/catkin_ws/src/Active-ORB-SLAM2/include/System.h:30,
                 from /home/wr/catkin_ws/src/Active-ORB-SLAM2/src/System.cc:23:
/home/wr/catkin_ws/src/Active-ORB-SLAM2/include/OctomapBuilder.h:15:31: fatal error: octomap/OcTreeLUT.h: 没有那个文件或目录
compilation terminated.
CMakeFiles/ORB_SLAM2.dir/build.make:62: recipe for target 'CMakeFiles/ORB_SLAM2.dir/src/System.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/System.cc.o] Error 1
CMakeFiles/Makefile2:289: recipe for target 'CMakeFiles/ORB_SLAM2.dir/all' failed
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TengFeiHan0** [comment]
```
 ```
I got an error as follows, does anyone has encountered this question? thank you in advance.@XinkeAE @WR0903 @zzx9636 

```
```
```
error: no matching function for call to ‘ompl::tools::SelfConfig::getDefaultNearestNeighbors(ompl::geometric::RRT*)’
        nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion *>(this));
                                                                              ^
In file included from /home/htf/Downloads/Active-ORB-SLAM2-octomap/src/myRRT.cc:36:0:
/opt/ros/indigo/include/ompl/tools/config/SelfConfig.h:93:42: note: candidate: template<class _T> static ompl::NearestNeighbors<_T>* ompl::tools::SelfConfig::getDefaultNearestNeighbors(const StateSpacePtr&)
             static NearestNeighbors<_T>* getDefaultNearestNeighbors(const base::StateSpacePtr &space)
                                          ^
/opt/ros/indigo/include/ompl/tools/config/SelfConfig.h:93:42: note:   template argument deduction/substitution failed:
/home/htf/Downloads/Active-ORB-SLAM2-octomap/src/myRRT.cc:80:78: note:   cannot convert ‘(ompl::geometric::RRT*)this’ (type ‘ompl::geometric::RRT*’) to type ‘const StateSpacePtr& {aka const boost::shared_ptr<ompl::base::StateSpace>&}’
        nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion *>(this));
                                                                              ^

```

```

**Comment by zzx9636** [comment]
@TengFeiHan0 Did you install your OMPL through ROS? Can you try to remove previous OMPL installation and re-install follow this link [http://ompl.kavrakilab.org/installation.html](http://ompl.kavrakilab.org/installation.html)? Let me know if there are more problems.

**Comment by TengFeiHan0** [comment]
at first, I reinstalled the OMPL by typing` sudo apt-get install ros-`rosversion -d`-ompl` and `./install-ompl-ubuntu.sh`. Unfortunately, this error still exists.@zzx9636

**Comment by zzx9636** [comment]
Sorry. I did not make it clear in the last post. Can you try to remove ROS-indigo-ompl  and then use the shell file to install it? 
If it still doesn’t work, I may try to reproduce this compiling error on my own computer to see what happens.

**Comment by TengFeiHan0** [comment]
I followed your recommendations, but it will causes another error.
```
Could not find a package configuration file provided by "OMPL" with any of
  the following names:

    OMPLConfig.cmake
    ompl-config.cmake

``
```
then I typed `sudo apt-get install ros-`rosversion -d`-ompl`the previous problem was fixed. in my opinion, if we want to use OMPL, we have to install` ros-indigo-ompl`

**Comment by zzx9636** [comment]
Thanks for the update. I am glad to hear your problem has been solved.

**Comment by TengFeiHan0** [comment]
I am sorry about the misunderstanding sentences, I mean this error ```
```
Could not find a package configuration file provided by "OMPL" with any of
  the following names:

    OMPLConfig.cmake
    ompl-config.cmake
``` 
was solved by typing ```ros-indigo-ompl`
```However, the original problem still exists. besides, you recommanded that I should remove` ros-indigo-ompl` when compiling the whole project. 
@zzx9636

**Comment by zzx9636** [comment]
@TengFeiHan0 I think this error means your CMake cannot find OMPL. Here is the discussion from another repository [https://github.com/ros-planning/moveit/issues/169](https://github.com/ros-planning/moveit/issues/169). If you would like to play around with cmakelist, I believe you can solve it. Maybe this[ link](http://ompl.kavrakilab.org/buildSystem.html) will help. Otherwise, I will try to reproduce this error on a fresh installed Ubuntu this weekend to see what is the best way to install OMPL.

**Comment by TengFeiHan0** [comment]
yes, you're right.  I solved this error. But the original error still exists. that's the question I want to address eventually.@zzx9636
```
error: no matching function for call to ‘ompl::tools::SelfConfig::getDefaultNearestNeighbors(ompl::geometric::RRT*)’
        nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion *>(this));
                                                                              ^
In file included from /home/htf/Downloads/Active-ORB-SLAM2-octomap/src/myRRT.cc:36:0:
/opt/ros/indigo/include/ompl/tools/config/SelfConfig.h:93:42: note: candidate: template<class _T> static ompl::NearestNeighbors<_T>* ompl::tools::SelfConfig::getDefaultNearestNeighbors(const StateSpacePtr&)
             static NearestNeighbors<_T>* getDefaultNearestNeighbors(const base::StateSpacePtr &space)
                                          ^
/opt/ros/indigo/include/ompl/tools/config/SelfConfig.h:93:42: note:   template argument deduction/substitution failed:
/home/htf/Downloads/Active-ORB-SLAM2-octomap/src/myRRT.cc:80:78: note:   cannot convert ‘(ompl::geometric::RRT*)this’ (type ‘ompl::geometric::RRT*’) to type ‘const StateSpacePtr& {aka const boost::shared_ptr<ompl::base::StateSpace>&}’
        nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion *>(this));
                                                                              ^
```

**Comment by TengFeiHan0** [comment]
> yes, you're right. I solved this error. But the original error still exists. that's the question I want to address eventually.@zzx9636
> 
> ```
> error: no matching function for call to ‘ompl::tools::SelfConfig::getDefaultNearestNeighbors(ompl::geometric::RRT*)’
>         nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion *>(this));

I  replaced `(this)` with` (si_->getStateSpace())`, then it can works. `nn_.reset(tools::SelfConfig::getDefaultNearestNeighbors<Motion*>(si_->getStateSpace());`
However, In myRRTstar.cpp
I also got a couple of unexpected errors as follows:
```
myRRTstar.cc:151:27: error: ‘class ompl::base::SpaceInformation’ has no member named ‘getSpaceMeasure’
     prunedMeasure_ = si_->getSpaceMeasure();
                           ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘virtual ompl::base::PlannerStatus ompl::geometric::RRTstar::solve(const ompl::base::PlannerTerminationCondition&)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:494:35: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘isFinite’
                         if (opt_->isFinite(bestCost_) == false)
                                   ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘int ompl::geometric::RRTstar::pruneTree(const ompl::base::Cost&)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:695:15: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘isFinite’
     if (opt_->isFinite(prunedCost_))
               ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘ompl::base::Cost ompl::geometric::RRTstar::solutionHeuristic(const ompl::geometric::RRTstar::Motion*) const’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:896:32: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘betterCost’
             costToCome = opt_->betterCost(costToCome, opt_->motionCost(startMotions_.at(i)->state, motion->state)); // lower-bounding cost from the start to the state
                                ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘void ompl::geometric::RRTstar::setTreePruning(bool)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:912:19: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘hasCostToGoHeuristic’
         if (opt_->hasCostToGoHeuristic() == false)
                   ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘void ompl::geometric::RRTstar::setPrunedMeasure(bool)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:932:19: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘hasCostToGoHeuristic’
         if (opt_->hasCostToGoHeuristic() == false)
                   ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:959:39: error: ‘class ompl::base::SpaceInformation’ has no member named ‘getSpaceMeasure’
                 prunedMeasure_ = si_->getSpaceMeasure();
                                       ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘void ompl::geometric::RRTstar::setInformedSampling(bool)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:975:19: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘hasCostToGoHeuristic’
         if (opt_->hasCostToGoHeuristic() == false)
                   ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘void ompl::geometric::RRTstar::setSampleRejection(bool)’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:1022:19: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘hasCostToGoHeuristic’
         if (opt_->hasCostToGoHeuristic() == false)
                   ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc: In member function ‘void ompl::geometric::RRTstar::allocSampler()’:
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:1060:29: error: ‘class ompl::base::OptimizationObjective’ has no member named ‘allocInformedStateSampler’
         infSampler_ = opt_->allocInformedStateSampler(pdef_, numSampleAttempts_);
                             ^
/home/htf/Downloads/Active-ORB-SLAM2-master/src/myRRTstar.cc:1066:21: error: no match for ‘operator=’ (operand types are ‘ompl::base::InformedSamplerPtr {aka boost::shared_ptr<ompl::base::InformedSampler>}’ and ‘std::shared_ptr<ompl::base::RejectionInfSampler>’)
         infSampler_ = std::make_shared<base::RejectionInfSampler>(pdef_, numSampleAttempts_);
```
I found that these function are members of class `ompl::base::OptimizationObjective ompl::base::SpaceInformation` then I tried to add the related header file at the top of myRRTstar.cpp.
nevertheless,  It doesn't make sense.
In my opinion, some problems are existing in myRRT.cpp and myRRTstar.cpp.@zzx9636

For example
[line216   getSpaceMeasure](http://ompl.kavrakilab.org/base_2SpaceInformation_8h_source.html)
I already added the conresponding header files, it still cannot find the conresponded functions, which makes confusing.

**Comment by gaunthan** [comment]
`octomap/OcTreeLUT.h` was removed from OctoMap 1.8.0.

Installing order version of OctoMap (e.g. , [OctoMap 1.7.2](https://github.com/OctoMap/octomap/archive/v1.7.2.zip)) will solve the problem.

**Comment by gaunthan** [comment]
> `octomap/OcTreeLUT.h` was removed from OctoMap 1.8.0.
> 
> Installing order version of OctoMap (e.g. , [OctoMap 1.7.2](https://github.com/OctoMap/octomap/archive/v1.7.2.zip)) will solve the problem.

I have integrated the package in [gaunthan/Active-ORB-SLAM2](https://github.com/gaunthan/Active-ORB-SLAM2.git) and passed the building (both `build.sh` and `build_ros.sh`) on my platform (ubuntu 18.04 with ros-melodic).

Check it out!

**Comment by XunshanMan** [comment]
> I am sorry about the misunderstanding sentences, I mean this error ```
> 
> ```
> Could not find a package configuration file provided by "OMPL" with any of
>   the following names:
> 
>     OMPLConfig.cmake
>     ompl-config.cmake
> ```
> 
> was solved by typing `` ros-indigo-ompl` ``However, the original problem still exists. besides, you recommanded that I should remove` ros-indigo-ompl` when compiling the whole project.
> @zzx9636

After I changed " FindPackage( OMPL REQUIRED )" to "FindPackage( ompl REQUIRED )" in CMakeLists.txt, the problem was solved. Because I found the name of the conifg file is omplConfig.cmake, which means it's lowercase.
